### ISSUE TITLE
Dudas del proyecto. 

### ISSUE THREAD

**Issue by willian20091** [EstebanFuentealba/ISSD-SNES-ROM-Web-Editor#2]
Hola @EstebanFuentealba, estaba buscando una forma de editar la rom ISSSD, pero como uso un Mac con M1, no puedo usar las herramientas de Windows. Inicialmente quiero felicitarte por tu trabajo. Lástima que no puedas completar todas las funciones TODO.

No tengo muchos conocimientos en esta área de la edición de roms, ¿qué me recomendarían para iniciar mis estudios?

**Comment by EstebanFuentealba** [comment]
Este proyecto fue uno de los primeros que empecé, mas que nada era como hobbie, después cree https://github.com/EstebanFuentealba/web-iss-studio que es algo mas avanzado ya la idea era poder modificar información y graficas del ROM desde la web, aunque tampoco lo retomé. Me estaba basando en el proyecto de https://github.com/rodmguerra/issparser que está en Java, pero lo quise llevar a la web. 
Sólo alcancé a mostrar la información pero se puede continuar para implementar las otras funciones.

https://github.com/user-attachments/assets/9a082416-48d5-4ee9-907f-6736b13449c2

**Comment by EstebanFuentealba** [comment]
Estos son algunos recursos que encontré en ese tiempo para modificar las ROM, hay muchos que ya no están en internet y que te pueden ser de ayuda


[ISSD Hex.docx](https://github.com/user-attachments/files/16731253/ISSD.Hex.docx)

[TUTORIAL EDITANDO ESCUDOS FB 96.docx](https://github.com/user-attachments/files/16731254/TUTORIAL.EDITANDO.ESCUDOS.FB.96.docx)

[Editor FB 2009.zip](https://github.com/user-attachments/files/16731257/Editor.FB.2009.zip)

[Editando Textos no FB.zip](https://github.com/user-attachments/files/16731292/Editando.Textos.no.FB.zip)

[Editando Cores no FB_.docx](https://github.com/user-attachments/files/16731274/Editando.Cores.no.FB_.docx)

[Starter-Romhacking-Guide-based-on-Super_Copa2017-ISSD.pdf](https://github.com/user-attachments/files/16731275/Starter-Romhacking-Guide-based-on-Super_Copa2017-ISSD.pdf)

[Inserindo uma Intro em uma ROM de SNES.pdf](https://github.com/user-attachments/files/16731278/Inserindo.uma.Intro.em.uma.ROM.de.SNES.pdf)
[Intro.zip](https://github.com/user-attachments/files/16731329/Intro.zip)

[LunarExpand114.zip](https://github.com/user-attachments/files/16731308/LunarExpand114.zip)


[SNESPal.zip](https://github.com/user-attachments/files/16731325/SNESPal.zip)

**Comment by willian20091** [comment]
Muchas gracias @EstebanFuentealba , esto me ayudará mucho a continuar con el proyecto.
